version: "3.8"

services:
  site1:
    image: registry.cn-hangzhou.aliyuncs.com/houhongxu/site:latest
    container_name: site1
    ports:
      - "81:80" # 映射主机的 81 端口到容器的 80 端口
    volumes:
      - shared_volume:/usr/share/nginx/html # 将主机上的 dist 目录挂载到 Nginx 容器的默认 HTML 目录
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - site-network
  
  site2:
    image: registry.cn-hangzhou.aliyuncs.com/houhongxu/site:latest
    container_name: site2
    ports:
      - "82:80" # 映射主机的 82 端口到容器的 80 端口
    volumes:
      - shared_volume:/usr/share/nginx/html # 将主机上的 dist 目录挂载到 Nginx 容器的默认 HTML 目录
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - site-network
  
  site3:
    image: registry.cn-hangzhou.aliyuncs.com/houhongxu/site:latest
    container_name: site3
    ports:
      - "83:80" # 映射主机的 83 端口到容器的 80 端口
    volumes:
      - shared_volume:/usr/share/nginx/html # 将主机上的 dist 目录挂载到 Nginx 容器的默认 HTML 目录
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - site-network

volumes:
  shared_volume:

networks:
  site-network:
