name: build-and-push-docker-image

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4

      - run: pnpm i

      - run: pnpm build

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_USERNAME }}/site:latest

      - run: |
          echo "🐳 Docker image pushed successfully to Aliyun!"
